name: exp_0
description: ''
model_name: FSRST
dataset: RefDataset
paths:
  train: '/home/varun/datasets/DFD/DFD_images_small/train' #'/home/varun/datasets/CelebAMask-HQ/train' '/home/varun/datasets/DFD_images_small/train'
  valid: '/home/varun/datasets/DFD/DFD_images_small/valid' # '/home/varun/datasets/CelebAMask-HQ/valid' '/home/varun/datasets/DFD_images_small/valid'
  checkpoints: 'checkpoints'
model:
  nc: 64  # 64 for HIMEv2 and 32 for STAlign
  uf: 4  # 4 8
  lr: 32  # 32 16
train:
  use_ref: true
  use_hr_as_ref: false
  seed: 13
  batch_size: 8 #512
  device: cuda
  hr_size: 128
  lr_size: 32  # 32 16
  learning_rate: 0.0001 # 0.0001 0.00005 0.000025 0.00001
  offset_lr: 0.00001 # 0.00001 0.000005 0.000001
  scheduler: true
  steps: [600, 900]  # because in exp_28 the best results were around 400 mark
  gamma: 0.5
  epoch_start: 0
  epochs: 1000
  valid_epoch: 5
  save_epoch: 100
  save_best: true
  save_thresh: 0.021  # 0.021  0.0139
